### ISSUE TITLE
A lot of brands

### ISSUE THREAD

**Issue by galengidman** [brandcolors/feedback#218]
Sent to me via email. Some already are on the site, but plan on releasing these along with the new version of the site.

- 500px: #000000
- aboutme: #00405d
- amazon: #ff9900
- angellist: #7fbb00
- answers: #136ad5
- appstore: #5e5e5f
- bebo: #ee1011
- behance: #1769ff
- blogger: #f57d00
- blogrss: #ff9933
- crunchbase: #2292a7
- delicious: #3399ff
- deviantart: #4e6252
- digg: #000000
- dribbble: #ea4c89
- ebay: #0064d2
- elance: #0067b1
- ello: #000000
- etsy: #d5641c
- facebook: #3b5998
- facebookpage: #3b5998
- fivehundredpx: #00aeef
- flavorsme: #f10087
- flickr: #ff0084
- flixster: #2971b2
- follr: #006699
- foursquare: #8fd400
- friendfeed: #2f72c4
- friendster: #009444
- goldmail: #ffc10e
- goodreads: #ecebd9
- google: #4285f4
- googlebuzz: #dd4b39
- googlecalendar: #4285f4
- googledrive: #0f9d58
- googlemaps: #4285f4
- googleplay: #f4b400
- googleplus: #db4437
- googlepluspage: #db4437
- googlereader: #f4b400
- hi5: #fbad05
- hyves: #f79634
- imdb: #f5de50
- klout: #01b9ff
- lastfm: #c3000d
- linkedin: #0976b4
- livejournal: #8f499c
- meetup: #e0393e
- mybloglog: #2b7385
- myspace: #030303
- netflix: #b9090b
- netvibes: #39bd00
- ning: #76ae49
- orkut: #ec1b90
- photobucket: #0ea0db
- picasa: #448afc
- picplz: #00aeef
- pinterest: #cc2127
- plaxo: #424f5c
- plancast: #3884d0
- plurk: #cf682f
- posterous: #ffe278
- quora: #a82400
- reddit: #ff4500
- resumebucket: #3a70bc
- rounds: #f4c32e
- scribd: #1a7bba
- second_life: #ff781b
- seekingalpha: #431414
- seesmic: #ffb308
- shelfari: #99cde7
- slideshare: #01adaf
- soundcloud: #ff8800
- spotify: #7ab800
- stackoverflow: #fe7a15
- stumbleupon: #eb4924
- technorati: #339900
- tokbox: #1e1916
- trulia: #5eab1f
- tumblr: #35465c
- tungle: #c50a1d
- twitter: #55acee
- typepad: #d2de61
- upcoming: #2bde73
- viadeo: #ec7500
- vimeo: #1ab7ea
- visualcv: #2c3f62
- visually: #0cacd8
- vkontakte: #54769b
- wordpress: #21759b
- xanga: #50ac41
- xing: #cfdc00
- xinxii: #f67a09
- yanswers: #342163
- yedda: #2992a7
- yelp: #af0606
- youtube: #b31217
- zillow: #0074e4

**Comment by dkhamsing** [comment]
nice

**Comment by dkhamsing** [comment]
these will need to be added.. wip

- [ ] angellist: #7fbb00
- [ ]  answers: #136ad5
- [ ]  appstore: #5e5e5f
- [ ] bebo: #ee1011
- [ ] blogrss: #ff9933
- [ ] crunchbase: #2292a7
- [ ] digg: #000000
- [ ] elance: #0067b1
- [ ] ello: #000000
- [ ] facebookpage: #3b5998
- [ ] flavorsme: #f10087

to process below..

flickr: #ff0084
flixster: #2971b2
follr: #006699
foursquare: #8fd400
friendfeed: #2f72c4
friendster: #009444
goldmail: #ffc10e
goodreads: #ecebd9
google: #4285f4
googlebuzz: #dd4b39
googlecalendar: #4285f4
googledrive: #0f9d58
googlemaps: #4285f4
googleplay: #f4b400
googleplus: #db4437
googlepluspage: #db4437
googlereader: #f4b400
hi5: #fbad05
hyves: #f79634
imdb: #f5de50
klout: #01b9ff
lastfm: #c3000d
linkedin: #0976b4
livejournal: #8f499c
meetup: #e0393e
mybloglog: #2b7385
myspace: #030303
netflix: #b9090b
netvibes: #39bd00
ning: #76ae49
orkut: #ec1b90
photobucket: #0ea0db
picasa: #448afc
picplz: #00aeef
pinterest: #cc2127
plaxo: #424f5c
plancast: #3884d0
plurk: #cf682f
posterous: #ffe278
quora: #a82400
reddit: #ff4500
resumebucket: #3a70bc
rounds: #f4c32e
scribd: #1a7bba
second_life: #ff781b
seekingalpha: #431414
seesmic: #ffb308
shelfari: #99cde7
slideshare: #01adaf
soundcloud: #ff8800
spotify: #7ab800
stackoverflow: #fe7a15
stumbleupon: #eb4924
technorati: #339900
tokbox: #1e1916
trulia: #5eab1f
tumblr: #35465c
tungle: #c50a1d
twitter: #55acee
typepad: #d2de61
upcoming: #2bde73
viadeo: #ec7500
vimeo: #1ab7ea
visualcv: #2c3f62
visually: #0cacd8
vkontakte: #54769b
wordpress: #21759b
xanga: #50ac41
xing: #cfdc00
xinxii: #f67a09
yanswers: #342163
yedda: #2992a7
yelp: #af0606
youtube: #b31217
zillow: #0074e4

**Comment by galengidman** [comment]
Thanks for sorting through this. Let's skip everything in your "not sure if should be added list" and go ahead and go ahead with the Digg and Ello. Will review and publish the others shortly.

**Comment by galengidman** [comment]
Sorry, didn't mean to close...

**Comment by dkhamsing** [comment]
ok

**Comment by dkhamsing** [comment]
still goin thru it..

**Comment by creativejuiz** [comment]
Hi there !
Two other brands I was looking for : 

- [] viadeo: #C0660E , #000
- [] digg: #000, #0093CC

Thank you for your work!
G.

**Comment by dkhamsing** [comment]
THanks @creativejuiz - will try to add em

**Comment by dkhamsing** [comment]
@galengidman 
can you update the following

1. digg 0093CC

**Comment by galengidman** [comment]
@dkhamsing Digg looks like #000 to me. They're using those buttons, but I'm not even sure they're part of the brand.

**Comment by dkhamsing** [comment]
Uh oops yeah that is true

**Comment by brandonmcconnell** [comment]
The actual colors for viadeo are #000 , #ef7703

**Comment by brandonmcconnell** [comment]
Other brand colors:
- **[Fancy](http://fancy.com/):** #46a5e3 , #fff
- **[McDonalds](http://mcdonalds.com/):** #ffC82e , #d90e00
- **[BurgerKing](http://burgerking.com/):** #1A4593 , #e8012f , #f8bd00
- **[DentalPlans](http://dentalplans.com/):** #00a7b5 , #ff9e1b
- **[Subway](http://subway.com/):** #1e5142 , #fff , #ffec00
- **[Wendy's](http://wendys.com/):** #d1212e , #40ccf0 , #000 , #fff

**Comment by dkhamsing** [comment]
Thanks, will take a look

@galengidman do you think fff should be added for the above

**Comment by galengidman** [comment]
@dkhamsing No, I never add white. Black, but not white.

**Comment by brandonmcconnell** [comment]
K just disregard the white

**Comment by dkhamsing** [comment]
Got it

Will add/update the following

- [ ] The actual colors for viadeo are #000 , #ef7703
- [ ] Fancy: #46a5e3 , #fff
- [ ] McDonalds: #ffC82e , #d90e00
- [ ] BurgerKing: #1A4593 , #e8012f , #f8bd00
- [ ] DentalPlans: #00a7b5 , #ff9e1b
- [ ] Subway: #1e5142 , #fff , #ffec00
- [ ] Wendy's: #d1212e , #40ccf0 , #000 , #fff

Thanks @brandonmcconnell @galengidman

**Comment by dkhamsing** [comment]
still goin thru it..

these are not on http://brandcolors.net

to submit/submitted for review
- [x]  answers: #136ad5
- [x] bebo: #ee1011
- [x] crunchbase: #2292a7
- [x] elance: #0067b1
- [x] digg: #000000
- [x] ello: #000000
- [ ] facebookpage: #3b5998
- [x] flavorsme: #f10087
- [x] flixster: #2971b2
- [ ] goodreads: #ecebd9
- [ ] googlebuzz: #dd4b39
- [ ] googlecalendar: #4285f4
- [ ] googledrive: #0f9d58
- [ ] googlemaps: #4285f4
- [ ] googleplay: #f4b400
- [ ] googlepluspage: #db4437
- [ ] googlereader: #f4b400
- [x] hi5: #fbad05
- [ ] myspace: #030303
- [x] netvibes: #39bd00
- [ ] ning: #76ae49
- [ ] orkut: #ec1b90
- [x] photobucket: #0ea0db
- [x] plaxo: #424f5c
- [ ] resumebucket: #3a70bc
- [ ] rounds: #f4c32e
- [x] scribd: #1a7bba
- [ ] seekingalpha: #431414
- [ ] shelfari: #99cde7
- [ ] tokbox: #1e1916
- [x] tungle: #c50a1d
- [x] typepad: #d2de61
- [ ] viadeo: #ec7500
- [ ] visualcv: #2c3f62
- [ ] visually: #0cacd8
- [ ] xanga: #50ac41


not a brand
- blogrss: #ff9933

not sure if should be added
- [ ] follr: #006699
- [ ] yanswers: #342163 same as yahoo??

rip
- goldmail: #ffc10e

**Comment by dkhamsing** [comment]
@galengidman can u give these a quick look.. should they be added?

- [ ] facebookpage: #3b5998
- [ ] googlecalendar: #4285f4
- [ ] googledrive: #0f9d58
- [ ] googlemaps: #4285f4
- [ ] googleplay: #f4b400
- [ ] googlepluspage: #db4437
  
not a brand??
- blogrss: #ff9933
- rounds: #f4c32e

not sure if should be added
- [ ] follr: #006699
- [ ] yanswers: #342163 same as yahoo??

**Comment by galengidman** [comment]
Top 6, no.

blogrss, no.

Rounds, yes, but #FDD800

Follr, yes, but #4DC9F6, #F67019, #F53794, #537BC4, #ACC236

yanswers no

**Comment by dkhamsing** [comment]
submitted
- [x] rounds
- [x] foller

let's close out this issue
thanks

**Comment by galengidman** [comment]
You da man.

**Comment by dkhamsing** [comment]
:smile:
