### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by erikfiala** [brandcolors/feedback#919]
- [x] *Brand Name*: Meta
- [x] *Brand Colors*: 0082fb, 0064e0
- [x] *Brand URL*: http://meta.com
- [x] *Where/how you found the brand colors*: https://www.facebook.com/brand/resources/facebookcompany/company-brand

**Comment by FancyThemes** [comment]
Added
